# Licensed under a 3-clause BSD style license - see LICENSE.rst
"""ReStructuredText pages generated by the extension."""

__all__ = ["ExamplePage", "Renderer"]

from sphinx_example_index.pages._examplepage import ExamplePage
from sphinx_example_index.pages._templating import Renderer
