name: Python CI

on: [push, pull_request]

jobs:
  canary-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # setuptools_scm needs full history

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install tox
        run: python -m pip install tox

      - name: Run tox
        run: tox -e py-test-cov,codestyle,typing  # run tox using Python in path

  test:

    needs: [canary-test]

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.6
          - 3.7
          - 3.8
        tox-env:
          - cov
          - sphinx17
          - sphinx18
          - sphinx20
          - sphinx21
          - sphinx22
          - sphinx23
        exclude:
          # Exclude the canary-test job
          - python: 3.8
            tox-env: cov

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # setuptools_scm needs full history

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: python -m pip install tox

      - name: Run tox
        run: tox -e py-test-${{ matrix.tox-env }},typing  # run tox using Python in path

  docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # setuptools_scm needs full history

      - name: Install graphviz
        run: sudo apt-get install graphviz

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install tox
        run: python -m pip install tox

      - name: Run tox
        run: tox -e build_docs
