name: Bleeding-edge weekly CI

on:
  schedule:
    - cron: "0 4 * * MON"

jobs:
  ci:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - 3.6
          - 3.7
          - 3.8

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # setuptools_scm needs full history

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: python -m pip install tox

      - name: Run tox
        run: tox -e py-test-devdeps  # run tox using Python in path

  linkcheck:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # setuptools_scm needs full history

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install tox
        run: python -m pip install tox

      - name: Run tox
        run: tox -e linkcheck
