# Licensed under a 3-clause BSD style license - see LICENSE.rst
"""Support for creating unique identifiers for examples and related things."""

__all__ = [
    "format_title_to_example_id",
    "format_title_to_source_ref_id",
    "format_example_id_to_source_ref_id",
]

from docutils import nodes


def format_title_to_example_id(title: str) -> str:
    """Convert an example's title into an ID for the title.

    IDs are slugified versions of the title.

    Parameters
    ----------
    title : str
        The title of the example (such as set are the argument to the
        ``example`` directive.

    Returns
    -------
    example_id : str
        The ID for the example. This ID is used internally to identify an
        example within the build environment.
    """
    return nodes.make_id(title)


def format_title_to_source_ref_id(title: str) -> str:
    """Convert an example's title into the ref ID for the example's source
    location.

    The target node itself is generated by the ``example`` directive.

    Parameters
    ----------
    title : str
        The title of the example (such as set are the argument to the
        ``example`` directive.

    Returns
    -------
    ref_id : str
        The ref ID for the node marking the example's *source* location.
    """
    example_id = format_title_to_example_id(title)
    return format_example_id_to_source_ref_id(example_id)


def format_example_id_to_source_ref_id(example_id: str) -> str:
    """Convert an example's ID into the ref ID for the example's source
    location.

    The target node itself is generated by the ``example`` directive.

    Parameters
    ----------
    example_id : str
        The ID for the example. This ID is used internally to identify an
        example within the build environment.

    Returns
    -------
    ref_id : str
        The ref ID for the node marking the example's *source* location.
    """
    return "example-src-{}".format(example_id)
